export const API_BASE = 'https://api.spotify.com/v1';
export function parseSpotifyInput(input){const value=String(input||'').trim();let match=value.match(/^spotify:(track|album):([A-Za-z0-9]{22})$/);if(match)return{type:match[1],id:match[2]};try{const url=new URL(value);if(url.hostname==='open.spotify.com'){match=url.pathname.match(/^\/(track|album)\/([A-Za-z0-9]{22})(?:\/|$)/);if(match)return{type:match[1],id:match[2]};}}catch{}if(/^[A-Za-z0-9]{22}$/.test(value))return{type:null,id:value};throw new Error('Enter a Spotify track or album URL, URI, or 22-character ID.');}
export function parseTrackId(input){const parsed=parseSpotifyInput(input);if(parsed.type==='album')throw new Error('Expected a track, but received an album.');return parsed.id;}
export const trackUri=(id)=>`spotify:track:${id}`;
export const itemUri=(row)=>row?.item?.uri||row?.track?.uri||null;
export async function collectPages(firstUrl,request){const items=[];let url=firstUrl;while(url){const page=await request(url);items.push(...(page.items||[]));url=page.next;}return items;}
export function buildAlbumReplacements(sourceTracks,destinationTracks){if(sourceTracks.length!==destinationTracks.length)throw new Error(`The albums have different track counts (${sourceTracks.length} vs ${destinationTracks.length}), so they cannot be safely paired.`);const byPosition=new Map(destinationTracks.map(track=>[`${track.disc_number}:${track.track_number}`,track]));const replacements=sourceTracks.map(source=>{const destination=byPosition.get(`${source.disc_number}:${source.track_number}`);if(!destination)throw new Error(`No destination match for disc ${source.disc_number}, track ${source.track_number}: ${source.name}.`);return{sourceUri:source.uri,destinationUri:destination.uri,sourceName:source.name,destinationName:destination.name,position:`${source.disc_number}.${source.track_number}`};});if(new Set(replacements.map(item=>item.destinationUri)).size!==replacements.length)throw new Error('The album mapping is ambiguous. No changes were made.');return replacements;}
export function findTargets(playlists,contents,replacements){const sources=new Set(replacements.map(r=>r.sourceUri));const destinations=new Set(replacements.map(r=>r.destinationUri));return playlists.flatMap(playlist=>{const rows=contents.get(playlist.id);if(!rows)return[];const uris=rows.map(itemUri);const occurrences=uris.filter(uri=>sources.has(uri)).length;if(!occurrences)return[];return[{...playlist,occurrences,sourceUris:[...new Set(uris.filter(uri=>sources.has(uri)))],destinationUrisPresent:[...new Set(uris.filter(uri=>destinations.has(uri)))]}];});}
async function chunks(items,size,action){for(let i=0;i<items.length;i+=size)await action(items.slice(i,i+size));}
export async function runSafeMigration(targets,replacements,api){const bySource=new Map(replacements.map(r=>[r.sourceUri,r.destinationUri]));const results=targets.map(t=>({id:t.id,name:t.name,added:false,removed:false,addCount:0,removeCount:t.sourceUris.length,error:null}));for(let i=0;i<results.length;i++){const result=results[i],target=targets[i],present=new Set(target.destinationUrisPresent||[]);const needed=[...new Set(target.sourceUris.map(uri=>bySource.get(uri)).filter(uri=>uri&&!present.has(uri)))];try{await chunks(needed,100,uris=>api(`/playlists/${result.id}/items`,{method:'POST',body:JSON.stringify({uris})}));result.addCount=needed.length;result.added=true;}catch(error){result.error=error.message;}}if(results.some(r=>!r.added))return{phase:'add-failed',results};for(let i=0;i<results.length;i++){const result=results[i];try{await chunks(targets[i].sourceUris,100,uris=>api(`/playlists/${result.id}/items`,{method:'DELETE',body:JSON.stringify({items:uris.map(uri=>({uri}))})}));result.removed=true;}catch(error){result.error=error.message;}}return{phase:results.every(r=>r.removed)?'complete':'remove-partial',results};}
export async function runSafeSwap(targets,sourceUri,destinationUri,api){return runSafeMigration(targets.map(t=>({...t,sourceUris:t.sourceUris||[sourceUri],destinationUrisPresent:t.destinationUrisPresent||(t.destinationPresent?[destinationUri]:[])})),[{sourceUri,destinationUri}],api);}
